// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BugTrackerContext))]
    [Migration("20210617193120_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.Comment", b =>
                {
                    b.Property<Guid>("Comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment_text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Issue_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Post_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("User_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("User_id1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Comment_id");

                    b.HasIndex("Issue_id");

                    b.HasIndex("User_id1");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Models.Issue", b =>
                {
                    b.Property<Guid>("Issue_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Project_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Project_id1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("User_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("User_id1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Issue_id");

                    b.HasIndex("Project_id1");

                    b.HasIndex("User_id1");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Property<Guid>("Project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Project_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Project_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("First_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Comment", b =>
                {
                    b.HasOne("Domain.Models.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("Issue_id");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("User_id1");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Issue", b =>
                {
                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("Project_id1");

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Issues")
                        .HasForeignKey("User_id1");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Issue", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
